<?php
$section = "media";

include "../constants.php";

echo $head;
?>

<body>

<?php
echo $navbar;
echo $portrait;
echo $featuredarea;
?>

			<div class="main-with-sidebar">

<h3>Media coverage highlights</h3>
<table width="619px">
<tr>
	<td><a href='https://www.fastcompany.com/40441392/see-just-how-much-of-a-citys-land-is-used-for-parking-spaces'><img src='../images/logofastcompany.png' width='100' title='2017-07-20: Fast Company' alt='2017-07-20: Fast Company'></a></td>
	<td><a href='https://www.citylab.com/transportation/2017/07/a-visual-inventory-of-parking-lots/532677/'><img src='../images/logocitylab.png' width='100' title='2017-07-06: Citylab' alt='2017-07-06: Citylab'></a></td>
	<td><a href='http://www.huffingtonpost.com/tarun-wadhwa/could-lyft-and-uber-put-p_b_6172140.html'><img src='../images/logohuffpost.png' width='100' title='2015-01-17: The Huffington Post' alt='2015-01-17: The Huffington Post'></a></td>
	<td><a href='http://news.nationalgeographic.com/news/energy/2014/09/140902-taxi-sharing-study-mit/'><img src='../images/logonationalgeographic.png' width='100' title='2014-09-03: National Geographic' alt='2014-09-03: National Geographic'></a></td>
	<td><a href='http://www.nytimes.com/2014/09/02/science/sharing-taxis-nyc-mathematics.html'><img src='../images/logonewyorktimes.png' width='100' title='2014-09-01: The New York Times' alt='2014-09-01: The New York Times'></a></td>
	<td><a href='http://www.technologyreview.com/aroundmit/525246/social-medias-law-of-short-messages/'><img src='../images/logomittechnologyreview.png' width='100' title='2014-02-27: MIT Technology Review' alt='2014-02-27: MIT Technology Review'></a></td>
</tr>
</table>


<h3>Media coverage (selection)</h3>
	<table>
	    <!--<tr><td class='std col1 date'>2010-07</td><td class='std'>XXXXX</td><td class='std'>YYYYYY<br /><a href="ZZZZZZ"><div class="linkexternal">Online report</div></a></td></tr> -->
	    <tr><td class='std col1 date'>2022-06-23</td><td class='std'>Forskerforum</td><td class='std'> DATANØRDER HAR FUNDET KODEN TIL DET GODE FORSKNINGSMILJØ<br /><a href="https://www.forskerforum.dk/magasinet/2022/forskerforum-nr-4-2022"><div class="linkexternal">Online report</div></a> &nbsp; <a href="../downloads/article_forskerforum01.pdf"><div class="filepdf">Article</div></a></td></tr>
	    <tr><td class='std col1 date'>2022-06-21</td><td class='std'>Radio Ö1</td><td class='std'>Wissen Aktuell - Radwege verbessern durch Netzwerkforschung<br /><a href="https://oe1.orf.at/player/20220621/682503"><div class="linkexternal">Radio show</div></a> &nbsp; <a href="../downloads/radio_oe102.mp3"><div class="linkexternal">Recording</div></a></td></tr>
	    <tr><td class='std col1 date'>2022-06-02</td><td class='std'>Radio Ö1</td><td class='std'>Dimensionen - Planung funktionaler städtischer Radnetze<br /><a href="https://oe1.orf.at/player/20220602/681583/1654189908281"><div class="linkexternal">Radio show</div></a> &nbsp; <a href="../downloads/radio_oe101.mp3"><div class="linkexternal">Recording</div></a></td></tr>
	    <tr><td class='std col1 date'>2022-05-24</td><td class='std'>Kleine Zeitung</td><td class='std'>Stückwerk ist die schlechteste Strategie<br /><a href="https://www.kleinezeitung.at/auto/6134526/Radwegnetze-fuer-Staedte_Stueckwerk-ist-die-schlechteste-Strategie"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2022-05-13</td><td class='std'>futurezone</td><td class='std'>Wie man mehr Menschen zum Umstieg auf das Fahrrad bewegt<br /><a href="https://futurezone.at/science/menschen-umstieg-fahrrad-radfahren-radverkehr-netz-radwege-infrastruktur/402005559"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2022-05-04</td><td class='std'>Science ORF.at</td><td class='std'>Das optimale Radwegnetz<br /><a href="https://science.orf.at/stories/3212926/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2022-05-04</td><td class='std'>Vienna.at</td><td class='std'>Aufbau von Radweg-Netzen: "Schlechteste Wachstumsstrategie" auch in Wien<br /><a href="https://www.vienna.at/aufbau-von-radweg-netzen-schlechteste-wachstumsstrategie-auch-in-wien/7409311"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2022-03-28</td><td class='std'>ITU Copenhagen</td><td class='std'>New research may help improve Copenhagen’s bicycle infrastructure<br /><a href="https://en.itu.dk/About-ITU/Press/News-from-ITU/2022/Bicycle-networks-uk"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2022-02-04</td><td class='std'>Science ORF.at</td><td class='std'>Wie soziale Stabilität entsteht<br /><a href="https://science.orf.at/stories/3211308/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2022-01</td><td class='std'>Cyklister</td><td class='std'>BRUD I NETVÆRK sender cyklister ud til bilerne
i København<br /><a href="https://www.cyklistforbundet.dk/aktuelt/magasinet-cyklister/"><div class="linkexternal">Online report</div></a> &nbsp; <a href="../downloads/article_cyklister01.pdf"><div class="filepdf">Article</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-09-14</td><td class='std'>Scientific American</td><td class='std'>Simple Mathematical Law Predicts Movement in Cities around the World<br /><a href="https://www.scientificamerican.com/article/simple-mathematical-law-predicts-movement-in-cities-around-the-world/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-06-22</td><td class='std'>Le Monde</td><td class='std'>Une loi universelle régit la fréquentation des villes<br /><a href="https://www.lemonde.fr/sciences/article/2021/06/22/une-loi-universelle-regit-la-frequentation-des-villes_6085142_1650684.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-06-14</td><td class='std'>Physics World</td><td class='std'>Frequency and distance of human travel follows universal pattern, mobile-phone data reveals<br /><a href="https://physicsworld.com/a/frequency-and-distance-of-human-travel-follows-universal-pattern-mobile-phone-data-reveals/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-06-01</td><td class='std'>Frankfurter Allgemeine Zeitung</td><td class='std'>Die Vorhersagbarkeit menschlicher Bewegungsmuster<br /><a href="https://www.faz.net/aktuell/wissen/mobilitaetsforschung-die-vorhersagbarkeit-menschlicher-bewegungsmuster-17367914.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-31</td><td class='std'>Green Car Congress</td><td class='std'>MIT study: people globally follow a “visitation law”; inverse relationship between distance and frequency of visits<br /><a href="https://www.greencarcongress.com/2021/05/20210531-visitation.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-27</td><td class='std'>ITU Copenhagen</td><td class='std'>Meet the ITU researcher paving the way for a better bicycle infrastructure in cities<br /><a href="https://en.itu.dk/about-itu/press/news-from-itu/2021/meet-the-itu-researcher-paving-the-way-for-a-better-bicycle-infrastructure-in-cities"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-27</td><td class='std'>Der Spiegel</td><td class='std'>Das Universalgesetz der Straße<br /><a href="https://www.spiegel.de/wissenschaft/mensch/wie-sich-mit-handydaten-bewegungsstroeme-in-staedten-vorhersagen-lassen-a-1fd86fa8-711d-475d-8ef8-49ec05b38c55"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-27</td><td class='std'>Cosmos</td><td class='std'>New universal law of human mobility<br /><a href="https://cosmosmagazine.com/science/physics/new-universal-law-of-human-mobility/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-27</td><td class='std'>Público</td><td class='std'>Há um padrão universal na forma como as pessoas viajam nas cidades<br /><a href="https://www.publico.pt/2021/05/27/ciencia/noticia/ha-padrao-universal-forma-pessoas-viajam-cidades-1964033"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-27</td><td class='std'>Deutschlandfunk Nova</td><td class='std'>Mathematik - Eine Formel zur Bewegung von Menschen in Städten<br /><a href="https://srv.deutschlandradio.de/dlf-audiothek-audio-teilen.3265.de.html?mdm:audio_id=928693"><div class="linkexternal">Radio show</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>Scienmag</td><td class='std'>Mobility Data Reveals Universal Law Of Visitation In Cities<br /><a href="https://scienmag.com/mobility-data-reveals-universal-law-of-visitation-in-cities/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>MIT News</td><td class='std'>Study reveals a universal travel pattern across four continents<br /><a href="https://news.mit.edu/2021/travel-pattern-global-0526"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>Vice</td><td class='std'>Millions of People's Location Data Revealed a 'Universal' Pattern In Study<br /><a href="https://www.vice.com/en/article/epnzkm/millions-of-peoples-location-data-revealed-a-universal-pattern-in-study"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>Phys.Org</td><td class='std'>Mobility data reveals universal law of visitation in cities<br /><a href="https://phys.org/news/2021-05-mobility-reveals-universal-law-cities.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>The Academic Times</td><td class='std'>New law reveals deep global commonalities in how humans move through cities<br /><a href="https://academictimes.com/new-law-reveals-deep-global-commonalities-in-how-humans-move-through-cities/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>Bild der Wissenschaft</td><td class='std'>Universelles Muster menschlicher Mobilität entdeckt<br /><a href="https://www.wissenschaft.de/technik-digitales/universelles-muster-menschlicher-mobilitaet-entdeckt/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>Florida News Times</td><td class='std'>Mobility data reveals the universal law of visits in cities<br /><a href="https://floridanewstimes.com/mobility-data-reveals-the-universal-law-of-visits-in-cities/270983/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>nrc</td><td class='std'>Overal ter wereld reizen stedelingen in dezelfde patronen<br /><a href="https://www.nrc.nl/nieuws/2021/05/26/overal-ter-wereld-reizen-stedelingen-in-dezelfde-patronen-a4044987"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>Mirage.News</td><td class='std'>Study reveals a universal travel pattern across four continents<br /><a href="https://www.miragenews.com/study-reveals-a-universal-travel-pattern-across-566763/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>Autobus web</td><td class='std'>Scoperti schemi universali della mobilita’ in città<br /><a href="https://www.autobusweb.com/mobilita-scoperti-schemi-universali-della-mobilita-in-citta/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>Paudal</td><td class='std'>All over the world, city dwellers travel in the same patterns<br /><a href="https://www.paudal.com/2021/05/26/all-over-the-world-city-dwellers-travel-in-the-same-patterns/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>Limburger Zeitung</td><td class='std'>Die Studie zeigt ein globales Reisemuster auf vier Kontinenten<br /><a href="https://www.limburger-zeitung.de/die-studie-zeigt-ein-globales-reisemuster-auf-vier-kontinenten/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-05-26</td><td class='std'>Science Daily</td><td class='std'>Universal travel pattern across four continents<br /><a href="https://www.sciencedaily.com/releases/2021/05/210526115600.htm"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2021-05-26</td><td class='std'>Santa Fe Institute</td><td class='std'>Mobility data reveals universal law of visitation in cities<br /><a href="https://www.santafe.edu/news-center/news/mobility-data-reveals-universal-law-visitation-cities"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2021-03-08</td><td class='std'>Ingeniøren</td><td class='std'>Cykling i byen: Små investeringer i infrastruktur binder din by sammen<br /><a href="https://pro.ing.dk/mobilitytech/article/cykling-i-byen-smaa-investeringer-i-infrastruktur-binder-din-sammen-10256"><div class="linkexternal">Online report</div></a> &nbsp; <a href="../downloads/article_ingenioren01.pdf"><div class="filepdf">Article</div></a></td></tr>
		<tr><td class='std col1 date'>2020-05-21</td><td class='std'>The Guardian</td><td class='std'>Pollutionwatch: how bike roads can reduce exposure to toxic air<br /><a href="https://www.theguardian.com/environment/2020/may/21/pollutionwatch-how-bike-roads-can-reduce-exposure-to-toxic-air"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2018-10-26</td><td class='std'>Il Sole 24 Ore</td><td class='std'>Se l’automobile diventa un mezzo pubblico<br /><a href="https://www.ilsole24ore.com/art/tecnologie/2018-10-26/se-l-automobile-diventa-mezzo-pubblico-095955.shtml"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2018-10-22</td><td class='std'>Der Tagesspiegel</td><td class='std'>Ausstellung in Mitte eröffnet neue Blicke auf die Stadt<br /><a href="https://www.tagesspiegel.de/berlin/stadtentwicklung-in-berlin-ausstellung-in-mitte-eroeffnet-neue-blicke-aufdie-stadt/23217076.html"><div class="linkexternal">Online report</div></a> &nbsp; <a href="../downloads/article_dertagesspiegel01.pdf"><div class="filepdf">Article</div></a></td></tr>
	    <tr><td class='std col1 date'>2018-02-27</td><td class='std'>kurier</td><td class='std'>Die Macht der Frauennetzwerke<br /><a href="https://kurier.at/leben/die-macht-der-frauennetzwerke/311.868.902"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2017-08-31</td><td class='std'>trend</td><td class='std'>Frauen-Netzwerke: Schüchternheit ist keine Zier<br /><a href="https://www.trend.at/branchen/karrieren/frauen-netzwerke-schuechternheit-zier-8285830"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2017-07-21</td><td class='std'>Der Standard</td><td class='std'>Weniger Autos in der Stadt der Zukunft<br /><a href="http://derstandard.at/2000061580102/Weniger-Autos-in-der-Stadt-der-Zukunft"><div class="linkexternal">Online report</div></a> &nbsp; <a href="../downloads/article_derstandard04.pdf"><div class="filepdf">Article</div></a></td></tr>
	    <tr><td class='std col1 date'>2017-07-20</td><td class='std'>Fast Company</td><td class='std'>See Just How Much Of A City’s Land Is Used For Parking Spaces<br /><a href="https://www.fastcompany.com/40441392/see-just-how-much-of-a-citys-land-is-used-for-parking-spaces"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2017-07-09</td><td class='std'>Geoawesomeness</td><td class='std'>The Mobility Space Report: How much space do car parks take up in our cities?<br /><a href="http://geoawesomeness.com/how-much-space-do-cars-take-up-in-our-cities-the-mobility-space-report/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2017-07-06</td><td class='std'>Citylab</td><td class='std'>For 23 World Cities, a Visual Inventory of Parking Lots<br /><a href="https://www.citylab.com/transportation/2017/07/a-visual-inventory-of-parking-lots/532677/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2017-06-30</td><td class='std'>Daimler Innovation</td><td class='std'>Wenn aus Parkplätzen Bilder werden<br /><a href="https://www.daimler.com/innovation/specials/what-the-street.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2017-06-23</td><td class='std'>Mobility Lab</td><td class='std'>See how space for cars, trains, and bikes stacks up in New York City<br /><a href="https://mobilitylab.org/2017/06/23/space-cars-trains-bikes-nyc-moovel"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2017-06-23</td><td class='std'>Autonomous Vehicle Technology</td><td class='std'>New project visualizes mobility in international metropolises<br /><a href="http://www.autonomousvehicletech.com/articles/115-new-project-visualizes-mobility-in-international-metropolises"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2017-06-22</td><td class='std'>VISION mobility</td><td class='std'>Moovel erstellt interaktive Onlineplattform<br /><a href="http://www.vision-mobility.de/news-nachrichten/8792/moovel-erstellt-interaktive-onlineplattform"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2017-03-07</td><td class='std'>La Stampa</td><td class='std'>Car sharing: ecco le città più condivisibili<br /><a href="http://www.lastampa.it/2017/03/07/societa/car-sharing-ecco-le-citt-pi-condivisibili-HaLuC5SMAAjsQGWRKzOHuN/pagina.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2017-03-06</td><td class='std'>Nature News</td><td class='std'>Taxi-sharing in cities follows universal maths law<br /><a href="http://www.nature.com/news/taxi-sharing-in-cities-follows-universal-maths-law-1.21586"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2017-03-06</td><td class='std'>MIT News</td><td class='std'>Sharing the fares<br /><a href="http://news.mit.edu/2017/different-cities-similar-ride-sharing-potential-0306"><div class="linkexternal">Online report</div></a></td></tr>	    
	    <tr><td class='std col1 date'>2017-03-06</td><td class='std'>ScienceDaily</td><td class='std'>Very different cities have similar potential for ride sharing<br /><a href="https://www.sciencedaily.com/releases/2017/03/170306092719.htm"><div class="linkexternal">Online report</div></a></td></tr>	    
	    <tr><td class='std col1 date'>2017-01-02</td><td class='std'>IEEE Spectrum</td><td class='std'>Imagine New York City With 3,000 Taxis Instead of 13,000<br /><a href="http://spectrum.ieee.org/cars-that-think/transportation/efficiency/imagine-new-york-city-with-only-3000-minivans-instead-of-taxis-it-could-work"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2016-11-16</td><td class='std'>derStandard.at</td><td class='std'>Zeitalter des Teilens: Die Stadt gehört allen<br /><a href="http://derstandard.at/2000047541135/Im-Zeitalter-des-Teilens-Die-Stadt-gehoert-allen"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2016-09-07</td><td class='std'>Der Standard</td><td class='std'>Erfolg ist Neugier plus Zufall<br /><a href="../downloads/article_derstandard03.pdf"><div class="filepdf">Article</div></a></td></tr>
        <tr><td class='std col1 date'>2016-09-02</td><td class='std'>Wiener Zeitung</td><td class='std'>Big Data: wei&szlig;, m&auml;nnlich, jung<br /><a href="../downloads/article_wienerzeitung01.pdf"><div class="filepdf">Article</div></a></td></tr>
		<tr><td class='std col1 date'>2016-05-24</td><td class='std'>Curbed</td><td class='std'>The Future of Smart City Technology, From an MIT Professor<br /><a href="http://www.curbed.com/2016/5/24/11761274/smart-city-carlo-ratti-city-of-tomorrow"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2016-05-23</td><td class='std'>Motherboard Vice</td><td class='std'>Uber Wants Us to Think It's Environmentally Friendly, But Is It?<br /><a href="https://motherboard.vice.com/en_us/article/is-uber-good-or-bad-for-the-environment"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2016-03-27</td><td class='std'>The Guardian</td><td class='std'>The MIT lab flushing out a city’s secrets<br /><a href="https://www.theguardian.com/science/2016/mar/27/lab-that-flushes-out-city-secrets-massachusetts-mit-senseable-lab-sewage"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2016-01-29</td><td class='std'>orange.com research blog</td><td class='std'>Drawing boundaries of social interaction<br /><a href="https://recherche.orange.com/en/drawing-boundaries-of-social-interaction/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2015-10-19</td><td class='std'>Harvard Kennedy School Shorenstein Center</td><td class='std'>Uber, Airbnb and consequences of the sharing economy: Research roundup<br /><a href="http://journalistsresource.org/studies/economics/business/airbnb-lyft-uber-bike-share-sharing-economy-research-roundup"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2015-07-03</td><td class='std'>USA Today</td><td class='std'>Traffic claims from Uber and Lyft are tough to prove<br /><a href="http://www.usatoday.com/videos/money/business/2015/07/03/29663929/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2015-07-02</td><td class='std'>ScienceDaily</td><td class='std'>Uber And Lyft's Traffic Claims Are Tough To Prove<br /><a href="https://www.sciencedaily.com/videos/d900fa6a15c285d8f93a166144b56797.htm"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2015-07-02</td><td class='std'>Newsy</td><td class='std'>Uber And Lyft's Traffic Claims Are Tough To Prove<br /><a href="http://www.newsy.com/videos/uber-and-lyft-s-traffic-claims-are-tough-to-prove/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2015-01-17</td><td class='std'>The Huffington Post</td><td class='std'>Could Lyft and Uber Put Public Transit Out of Business?<br /><a href="http://www.huffingtonpost.com/tarun-wadhwa/could-lyft-and-uber-put-p_b_6172140.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-11-13</td><td class='std'>Forbes</td><td class='std'>Could Lyft And Uber Put Public Transit Out Of Business?<br /><a href="http://www.forbes.com/sites/tarunwadhwa/2014/11/13/will-lyft-and-ubers-shared-ride-service-put-public-transit-out-of-business/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2014-11-04</td><td class='std'>derStandard.at</td><td class='std'>Nicht nur in realer Welt: Bei 150 Freunden ist auch online Schluss<br /><a href="http://derstandard.at/2000007683904/Nicht-nur-in-realer-Welt-Bei-150-Freunden-ist-auch"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-11-04</td><td class='std'>Format</td><td class='std'>Auch online kann man bloß 150 Freunde haben<br /><a href="http://www.format.at/technik/facebook-freunde-5190646"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-11-04</td><td class='std'>Die Presse</td><td class='std'>Bei 150 Online-Freundschaften ist Schluss<br /><a href="http://diepresse.com/home/techscience/internet/4585916/Bei-150-OnlineFreundschaften-ist-Schluss-"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-11-02</td><td class='std'>The Huffington Post</td><td class='std'>Taking Rides With Strangers<br /><a href="http://www.huffingtonpost.com/steven-strogatz/taking-rides-with-strange_b_5754520.html"><div class="linkexternal">Online report</div></a></td></tr>
		<!--<tr><td class='std col1 date'>2014-11-04</td><td class='std'>krone.at</td><td class='std'>Bei 150 Freunden ist auch online Schluss<br /><a href="http://www.krone.at/Digital/Bei_150_Freunden_ist_auch_online_Schluss-Limit_fuer_Gehirn-Story-426059"><div class="linkexternal">Online report</div></a></td></tr>-->
	    <tr><td class='std col1 date'>2014-10-31</td><td class='std'>Science News</td><td class='std'>Even online, you can't have more than 150 friends<br /><a href="http://news.sciencemag.org/brain-behavior/2014/10/even-online-you-cant-have-more-150-friends"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2014-10-24</td><td class='std'>Conservation Magazine</td><td class='std'>A high-tech twist on carpooling<br /><a href="http://conservationmagazine.org/2014/10/a-high-tech-twist-on-carpooling/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-07</td><td class='std'>Salon</td><td class='std'>How to save America from cars: Start sharing them<br /><a href="http://www.salon.com/2014/09/07/how_to_save_america_from_cars_start_sharing_them/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-05</td><td class='std'>The Atlantic - Citylab</td><td class='std'>What Can We Learn From the Wealth of Virtual Nations?<br /><a href="http://www.citylab.com/tech/2014/09/what-can-we-learn-from-the-wealth-of-virtual-nations/379538/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-05</td><td class='std'>Science Friday</td><td class='std'>Hello, Stranger, Wanna Share a Cab?<br /><a href="http://www.sciencefriday.com/segment/09/05/2014/hello-stranger-wanna-share-a-cab.html"><div class="linkexternal">Radio show</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-03</td><td class='std'>The Brian Lehrer Show</td><td class='std'>Should We Start Sharing Taxis?<br /><a href="http://www.wnyc.org/story/should-we-start-sharing-taxis/"><div class="linkexternal">Radio show</div></a></td></tr>
	    <tr><td class='std col1 date'>2014-09-03</td><td class='std'>National Geographic</td><td class='std'>Taxi-Sharing Boosts Energy Efficiency, But Will Riders Get on Board?<br /><a href="http://news.nationalgeographic.com/news/energy/2014/09/140902-taxi-sharing-study-mit/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2014-09-02</td><td class='std'>Newsweek</td><td class='std'>Taxi Sharing Could Revolutionize New York City’s Transportation System<br /><a href="http://www.newsweek.com/taxi-sharing-could-revolutionize-new-york-citys-transportation-system-267592"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-02</td><td class='std'>Business Insider</td><td class='std'>Researchers Have Developed An Algorithm For Taxi Sharing That Could Revolutionize City Transport<br /><a href="http://www.businessinsider.com/algorithm-for-taxi-sharing-could-revolutionize-city-transport-2014-9"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-02</td><td class='std'>GeekWire</td><td class='std'>MIT study: Services like UberPool, Lyft Line cut transit time, pollution<br /><a href="http://www.geekwire.com/2014/mit-study-shows-services-like-uberpool-lyft-line-reduce-transit-time-pollution/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-01</td><td class='std'>The New York Times</td><td class='std'>If 2 New Yorkers Shared a Cab ...<br /><a href="http://www.nytimes.com/2014/09/02/science/sharing-taxis-nyc-mathematics.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2014-09-01</td><td class='std'>MIT News</td><td class='std'>Ride-sharing could cut cabs’ road time by 30 percent<br /><a href="http://newsoffice.mit.edu/2014/rideshare-data-cut-taxi-time-0901"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-01</td><td class='std'>derStandard.at</td><td class='std'>Taxi-Sharing spart Geld und Zeit<br /><a href="http://derstandard.at/2000005036964/Korallen-erzeugen-Wirbel-um-Nahrung-zu-bekommen-Taxi-Sharing-spart"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-01</td><td class='std'>Esmateria</td><td class='std'>Los taxistas podrían ganarle a Uber la guerra del ‘car-sharing’ si compartieran carreras<br /><a href="http://esmateria.com/2014/09/01/los-taxistas-podrian-ganarle-uber-la-guerra-del-car-sharing-si-compartieran-carreras/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-01</td><td class='std'>Phys.Org</td><td class='std'>Ride-sharing could cut cabs' road time by 30 percent<br /><a href="http://phys.org/news/2014-09-ride-sharing-cabs-road-percent.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-01</td><td class='std'>Fortune</td><td class='std'>Share a taxi with a stranger? Idea is catching in big cities<br /><a href="http://fortune.com/2014/09/01/share-a-taxi-with-a-stranger-idea-is-catching-in-big-cities/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-09-01</td><td class='std'>U.S. News</td><td class='std'>Going My Way? Taxi-Sharing Offers Big Benefits, Study Finds<br /><a href="http://www.usnews.com/news/articles/2014/09/01/taxi-sharing-could-cut-pollution-congestion-study-finds"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-04-07</td><td class='std'>Fast Company</td><td class='std'>Mapping A Year Of New York Taxi Rides Shows It’s Time To Start Sharing Cabs
<br /><a href="https://www.fastcompany.com/3028175/mapping-a-year-of-new-york-taxi-rides-shows-its-time-to-start-sharing-cabs"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-26</td><td class='std'>Mark Buchanan - Medium</td><td class='std'>Taxis 2.0: Streamlining city transport with graph theory<br /><a href="https://medium.com/the-physics-of-finance/taxis-2-0-streamlining-city-transport-with-graph-theory-1d6030320755"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-21</td><td class='std'>Fast Company</td><td class='std'>Infographic: Why We Should Share Cabs With Strangers<br /><a href="http://www.fastcodesign.com/3027939/slicker-city/infographic-why-we-should-share-cabs-with-strangers"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-19</td><td class='std'>MIT Technology Review</td><td class='std'>How Virtual Gaming Worlds Are Revealing the Nature of Human Hierarchies<br /><a href="http://www.technologyreview.com/view/525696/how-virtual-gaming-worlds-are-revealing-the-nature-of-human-hierarchies/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-19</td><td class='std'>Car Throttle</td><td class='std'>This Interactive View Of NYC Taxi Rides Is The Ultimate Map Porn<br /><a href="http://www.carthrottle.com/this-interactive-view-of-nyc-taxi-rides-is-the-ultimate-map-porn/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-19</td><td class='std'>Quattroruote</td><td class='std'>Audi e Mit studiano lo sharing dei taxi: "Meno corse, costi e CO2"<br /><a href="http://www.quattroruote.it/news/nuove_tecnologie/2014/03/19/new_york_audi_e_mit_studiano_lo_sharing_dei_taxi_meno_corse_costi_e_co2__0.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-18</td><td class='std'>infosthetics.com</td><td class='std'>HubCab: Mapping All Taxi Trips in New York during 2011<br /><a href="http://infosthetics.com/archives/2014/03/hubcab_mapping_all_taxi_trips_in_new_york_2011.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-15</td><td class='std'>habrahabr.ru</td><td class='std'>&#x0422;&#x0430;&#x043a;&#x0441;&#x0438; &#x0432; &#x041d;&#x044c;&#x044e;-&#x0419;&#x043e;&#x0440;&#x043a;&#x0435;: &#x0432;&#x0438;&#x0437;&#x0443;&#x0430;&#x043b;&#x0438;&#x0437;&#x0430;&#x0446;&#x0438;&#x044f; &#x043f;&#x0435;&#x0440;&#x0435;&#x043c;&#x0435;&#x0449;&#x0435;&#x043d;&#x0438;&#x0439; &#x0437;&#x0430; &#x0433;&#x043e;&#x0434;<br /><a href="http://habrahabr.ru/post/215881/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-15</td><td class='std'>BostInno</td><td class='std'>The More Excited We Are, the Shorter We Tweet<br /><a href="http://bostinno.streetwise.co/2014/03/15/tweet-bursts-out-of-mits-senseable-city-lab/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-15</td><td class='std'>psfk</td><td class='std'>How NYC could revolutionize urban transport by turning its taxi system into a sharing economy<br /><a href="http://www.psfk.com/2014/03/how-nyc-could-revolutionize-urban-transport-by-turning-its-taxi-system-into-a-sharing-economy.html#!zOtA1"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-14</td><td class='std'>HybridCars.com</td><td class='std'>Audi, MIT and GE Studying Data To Save Fuel<br /><a href="http://www.hybridcars.com/audi-mit-and-ge-studying-data-to-save-fuel/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-14</td><td class='std'>Automotive World</td><td class='std'>MIT, Audi launch HubCab project in New York City<br /><a href="http://www.automotiveworld.com/news-releases/mit-audi-launch-hubcab-project-new-york-city/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-14</td><td class='std'>Automotive Business Review</td><td class='std'>MIT, Audi and GE collaborate to launch transportation tracking tool<br /><a href="http://www.automotive-business-review.com/news/mit-audi-and-ge-collaborate-to-launch-hubcab-project-130314-4194820"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-13</td><td class='std'>Curbed NY</td><td class='std'>All 170 Million of New York City's Taxi Rides in 2011, Mapped!<br /><a href="http://ny.curbed.com/archives/2014/03/13/all_170_million_of_new_york_citys_taxi_rides_in_2011_mapped.php"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-12</td><td class='std'>New York Magazine</td><td class='std'>Beautiful Interactive Map Displays a Year of Taxi Rides<br /><a href="http://nymag.com/daily/intelligencer/2014/03/interactive-map-displays-a-year-of-taxi-rides.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-12</td><td class='std'>Gizmodo</td><td class='std'>A Whole Year of Taxi Rides in New York City Mapped<br /><a href="http://gizmodo.com/a-whole-year-of-taxi-rides-in-new-york-city-mapped-1542314862"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-12</td><td class='std'>Yahoo! Finance</td><td class='std'>MIT, Audi Launch HubCab Project in New York City<br /><a href="http://finance.yahoo.com/news/mit-audi-launch-hubcab-project-192327237.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-12</td><td class='std'>Atlantic Cities</td><td class='std'>How a System for Shared Taxi Rides Could Transform New York City<br /><a href="http://www.theatlanticcities.com/commute/2014/03/how-system-shared-taxi-rides-could-transform-new-york-city/8530/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-12</td><td class='std'>Xconomy</td><td class='std'>Hiding in 172M Cab Rides: A New Frontier for the ‘Sharing Economy’<br /><a href="http://www.xconomy.com/boston/2014/03/12/hiding-in-172m-cab-rides-a-new-frontier-for-the-sharing-economy/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-04</td><td class='std'>krone.at</td><td class='std'>Je aufgeregter man ist, desto k&uuml;rzer tweetet man<br /><a href="http://www.krone.at/Digital/Je_aufgeregter_man_ist._desto_kuerzer_tweetet_man-Forscher_zeigen_-Story-395696"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-03</td><td class='std'>Tiroler Tageszeitung</td><td class='std'>Gro&szlig;e Emotion - kurze Tweets: MIT-Forscher messen Massen-Aufregung<br /><a href="http://www.tt.com/home/8025255-91/gro%C3%9Fe-emotion---kurze-tweets-mit-forscher-messen-massen-aufregung.csp"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-03</td><td class='std'>derStandard.at</td><td class='std'>Gro&szlig;e Emotion - kurze Tweets: MIT-Forscher messen Massen-Aufregung<br /><a href="http://derstandard.at/1392686967903/Grosse-Emotion---kurze-Tweets-MIT-Forscher-messen-Massen-Aufregung"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-03</td><td class='std'>Wiener Zeitung</td><td class='std'>Erregung, Massenhysterie und Twitter<br /><a href="http://www.wienerzeitung.at/themen_channel/wz_digital/digital_life/612559_Erregung%C2%ADMassenhysterie%C2%ADund%C2%ADTwitter.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-03</td><td class='std'>Ö1 national radio</td><td class='std'>Wissen aktuell: Bei Aufregung wird k&uuml;rzer getwittert<br /><a href="http://oe1.orf.at/programm/365323"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2014-03-03</td><td class='std'>Science ORF.at</td><td class='std'>Bei Aufregung wird mehr, aber k&uuml;rzer getwittert<br /><a href="http://science.orf.at/stories/1734350/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-01</td><td class='std'>Malay Mail</td><td class='std'>Major events make for 'terser' tweets, say study<br /><a href="http://www.themalaymailonline.com/features/article/major-events-make-for-terser-tweets-say-study"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-03-01</td><td class='std'>CTV News</td><td class='std'>Major events leads to shorter tweets, online messages: study<br /><a href="http://www.ctvnews.ca/sci-tech/major-events-leads-to-shorter-tweets-online-messages-study-1.1709619"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-02-28</td><td class='std'>SocialTimes</td><td class='std'>The Long and the Short of Social Media &amp; Email Messages<br /><a href="http://socialtimes.com/long-short-social-media-email-messages_b143748"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-02-27</td><td class='std'>El Dinamo</td><td class='std'>Los tuiteos son más breves cuando estamos bajo presión según estudio<br /><a href="http://www.eldinamo.cl/2014/02/27/video-los-tuiteos-son-mas-breves-cuando-estamos-bajo-presion-segun-estudio/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-02-27</td><td class='std'>MIT Technology Review</td><td class='std'>Social Media’s Law of Short Messages<br /><a href="http://www.technologyreview.com/aroundmit/525246/social-medias-law-of-short-messages/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-02-27</td><td class='std'>CorpComms</td><td class='std'>Excited tweeters post shorter messages<br /><a href="http://www.corpcommsmagazine.co.uk/news/3487-excited-tweeters-post-shorter-messages"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-02-27</td><td class='std'>Zee News</td><td class='std'>Length of social-media messages proportional to public events: Study<br /><a href="http://zeenews.india.com/news/net-news/length-of-social-media-messages-proportional-to-public-events-study_914654.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-02-27</td><td class='std'>Business Standard</td><td class='std'>Length of social-media messages proportional to public events: Study<br /><a href="http://www.business-standard.com/article/news-ani/length-of-social-media-messages-proportional-to-public-events-study-114022700465_1.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-02-27</td><td class='std'>Il sole 24 ore</td><td class='std'>I percorsi sono condivisibili<br /><a href="http://nova.ilsole24ore.com/progetti/i-viaggi-sono-condivisibili"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-02-26</td><td class='std'>Phys.Org</td><td class='std'>Study finds social-media messages grow terser during major events<br /><a href="http://phys.org/news/2014-02-social-media-messages-terser-major-events.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2014-02-26</td><td class='std'>MIT News</td><td class='std'>Social media’s ‘law’ of short messages<br /><a href="http://mit.edu/newsoffice/2014/social-medias-law-of-short-messages-0226.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-02-18</td><td class='std'>MIT Technology Review</td><td class='std'>The Ties That Divide<br /><a href="http://www.technologyreview.com/article/524201/the-ties-that-divide/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2014-01</td><td class='std'>Publik-Forum EXTRA</td><td class='std'>Die Freundin meiner Freundin ist auch meine Freundin <br /><a href="http://shop.publik-forum.de/shop/?id=11872"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-12-30</td><td class='std'>MIT Technology Review</td><td class='std'>Telecommunications data show civic dividing lines in major countries<br /><a href="http://www.technologyreview.com/aroundmit/522961/telecommunications-data-show-civic-dividing-lines-in-major-countries/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-12-18</td><td class='std'>Atlantic Cities</td><td class='std'>The Lingering Power of Geography Over How We Communicate<br /><a href="http://www.theatlanticcities.com/technology/2013/12/uncanny-geography-phone-calls/7916/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-12-18</td><td class='std'>Science Daily</td><td class='std'>Telecommunications data show civic dividing lines in major countries<br /><a href="http://www.sciencedaily.com/releases/2013/12/131218171057.htm"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-12-18</td><td class='std'>MIT News</td><td class='std'>Telecommunications data show civic dividing lines in major countries<br /><a href="http://web.mit.edu/newsoffice/2013/telecommunications-data-show-civic-dividing-lines-in-major-countries-1218.html"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2013-06-19</td><td class='std'>Ö1 national radio</td><td class='std'>Dimensionen - Die Welt der Wissenschaft: Die Datentaucher<br /><a href="http://oe1.orf.at/programm/340732"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-04-24</td><td class='std'>Die Presse</td><td class='std'>Online spielen und forschen<br /><a href="http://pressespiegel.metacommunication.com/v3/clippings/pool/2013/04/24/_METAM450136674552895133240_20130424_Forschung36_39_wsna.pdf"><div class="filepdf">Article</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-27</td><td class='std'>Neue Zürcher Zeitung</td><td class='std'>Programmierter Altersdiabetes<br /><a href="http://www.nzz.ch/wissen/wissenschaft/programmierter-altersdiabetes-1.18053879"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-20</td><td class='std'>karpatinfo.net</td><td class='std'>Összefügg a cukorbetegség az éhínséggel<br /><a href="http://karpatinfo.net/cikk/tudomany/osszefugg-cukorbetegseg-az-ehinseggel"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-03-19</td><td class='std'>mno.hu</td><td class='std'>Összefügg a cukorbetegség az éhínséggel<br /><a href="http://mno.hu/betegszoba/osszefugg-a-cukorbetegseg-az-ehinseggel-1145479"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-03-15</td><td class='std'>Computerworld.ch</td><td class='std'>Frauen netzwerken anders<br /><a href="http://www.computerworld.ch/management/leadership/artikel/frauen-netzwerken-anders-62847/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-03-08</td><td class='std'>Kleine Zeitung</td><td class='std'>Hungernde Schwangere erhöhen Diabetes-Risiko bei Baby<br /><a href="http://www.kleinezeitung.at/magazin/wellness/3261042/hungernde-schwangere-erhoehen-diabetes-risiko-bei-baby.story"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-06</td><td class='std'>BioPortfolio</td><td class='std'>Famine in early life linked to diabetes in later life, researchers find<br /><a href="http://www.bioportfolio.com/news/article/1345512/Famine-in-early-life-linked-to-diabetes-in-later-life-researchers-find.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-06</td><td class='std'>InformationAboutDiabetes</td><td class='std'>Babies born during famine more likely to develop diabetes<br /><a href="http://www.informationaboutdiabetes.com/news/diabetes-research/babies-born-during-famine-more-likely-to-develop-diabetes"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-06</td><td class='std'>Die Presse</td><td class='std'>Medizin: Diabetes durch Hunger im Uterus<br /><a href="http://diepresse.com/home/science/1352885/Medizin_Diabetes-durch-Hunger-im-Uterus"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-06</td><td class='std'>Medical Xpress</td><td class='std'>Famine in early life linked to diabetes in later life, researchers find<br /><a href="http://medicalxpress.com/news/2013-03-famine-early-life-linked-diabetes.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-06</td><td class='std'>Salzburger Nachrichten</td><td class='std'>Hunger erhöht Risiko für Diabetes Typ 2<br /><a href="http://pressespiegel.metacommunication.com/v3/clippings/pool/2013/03/06/_METAO416136254667796990912_20130306_22_memw.pdf"><div class="linkexternal">Article</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-05</td><td class='std'>OÖ Nachrichten</td><td class='std'>Wenn Schwangere hungert, steigt bei Kind Diabetesrisiko<br /><a href="http://www.nachrichten.at/ratgeber/gesundheit/Wenn-Schwangere-hungert-steigt-bei-Kind-Diabetesrisiko;art114,1076431"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-05</td><td class='std'>derStandard.at</td><td class='std'>Massiv erhöhtes Diabetes-Risiko bei in Hungersnot Geborenen<br /><a href="http://derstandard.at/1362107450188/Massiv-erhoehtes-Diabetes-Risiko-bei-in-Hungersnot-Geborenen"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-05</td><td class='std'>Santa Fe Institute</td><td class='std'>Study: Famine in early life linked to diabetes in later life<br /><a href="http://www.santafe.edu/news/item/pnas-thurner-diabetes-and-famine/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-05</td><td class='std'>Wiener.Zeitung.at</td><td class='std'>Hungersnöte erhöhen späteres Diabetes-Risiko<br /><a href="http://www.wienerzeitung.at/themen_channel/wissen/mensch/529057_Hungersnoete-erhoehen-spaeteres-Diabetes-Risiko.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-05</td><td class='std'>paradisi.de</td><td class='std'>Hungernde Schwangerschaft erhöht Diabetes-Risiko bei Kindern<br /><a href="http://www.paradisi.de/Health_und_Ernaehrung/Erkrankungen/Diabetes/News/81474.php"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-05</td><td class='std'>Science ORF.at</td><td class='std'>Hunger vor der Geburt erhöht Diabetesrisiko<br /><a href="http://science.orf.at/stories/1713800/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-03-04</td><td class='std'>der.Standard.at</td><td class='std'>Geburt während Hungersnot erhöht Diabetes-Risiko deutlich<br /><a href="http://derstandard.at/1362107410949/Geburt-waehrend-Hungersnot-erhoeht-Diabetes-Risiko-deutlich"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-03-04</td><td class='std'>CIO</td><td class='std'>Wie wir uns in sozialen Netzwerken verhalten<br /><a href="http://www.cio.de/karriere/2906566/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-03-04</td><td class='std'>20 Minuten online</td><td class='std'>Hunger im Mutterleib führt zu Diabetes<br /><a href="http://www.20min.ch/wissen/news/story/Hunger-im-Mutterleib-fuehrt-zu-Diabetes-26983287"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-14</td><td class='std'>Express.be</td><td class='std'>Man en vrouw ook online verschillende sociale wezens<br /><a href="http://www.dutchcowboys.nl/online/27506"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-13</td><td class='std'>Express.be</td><td class='std'>Man en vrouw ook online verschillende sociale wezens<br /><a href="http://www.express.be/articles/nl/sciences/man-en-vrouw-ook-online-verschillende-sociale-wezens/186073.htm"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-12</td><td class='std'>Zeronovecinque</td><td class='std'>Come donne e uomini organizzano i social network<br /><a href="http://zeronovecinque.tumblr.com/post/42917677589/come-donne-e-uomini-organizzano-i-social-network#tumblr_notes"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-10</td><td class='std'>LizzyNet</td><td class='std'>Das Geschlecht virtueller Beziehungen<br /><a href="http://www.lizzynet.de/wws/das-geschlecht-virtueller-beziehungen.php"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-10</td><td class='std'>Onepakistan News</td><td class='std'>Men and women poles apart when it comes to style of social networking<br /><a href="http://pakistan.onepakistan.com.pk/news/sci-tech/179727-men-and-women-poles-apart-when-it-comes-to-style-of-social-networking.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-02-10</td><td class='std'>India Talkies</td><td class='std'>Men and women poles apart when it comes to style of social networking<br /><a href="http://www.indiatalkies.com/2013/02/men-women-poles-style-social-networking.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-02-10</td><td class='std'>sify news</td><td class='std'>Men and women poles apart when it comes to style of social networking<br /><a href="http://www.sify.com/news/men-and-women-poles-apart-when-it-comes-to-style-of-social-networking-news-international-ncklkpaafjb.html"><div class="linkexternal"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-02-10</td><td class='std'>The Preternatural Post</td><td class='std'>Organizing online social networks: Guys do it differently<br /><a href="http://www.preternaturalpost.com/2013/organizing-social-networks-online-guys-do-it-differently/"><div class="linkexternal"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-02-10</td><td class='std'>webindia123</td><td class='std'>Men and women poles apart when it comes to style of social networking<br /><a href="http://news.webindia123.com/news/Articles/India/20130210/2153572.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-02-10</td><td class='std'>Yahoo! Finance India</td><td class='std'>Men and women poles apart when it comes to style of social networking<br /><a href="http://in.finance.yahoo.com/news/men-women-poles-apart-comes-053641056.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-02-10</td><td class='std'>News Track India</td><td class='std'>Men and women poles apart when it comes to style of social networking<br /><a href="http://www.newstrackindia.com/newsdetails/2013/02/10/30-Men-and-women-poles-apart-when-it-comes-to-style-of-social-networking.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2013-02-09</td><td class='std'>Psych Tronics</td><td class='std'>How Men and Women Organize Their (Online) Social Networks Differently<br /><a href="http://www.psychtronics.com/2013/02/how-females-and-males-manage-their.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-09</td><td class='std'>Die Karrierebibel</td><td class='std'>Soziale Netzwerke: Frauen kommunizieren, Männer konkurrieren<br /><a href="http://karrierebibel.de/soziale-netzwerke-frauen-kommunizieren-manner-konkurrieren/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-09</td><td class='std'>United Academics</td><td class='std'>Women and Men Organize Social Networks Differently<br /><a href="http://www.united-academics.org/magazine/sex-society/women-and-men-organize-social-networks-differently/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-08</td><td class='std'>Phys.Org</td><td class='std'>How men and women organize their (online) social networks differently<br /><a href="http://phys.org/news/2013-02-men-women-online-social-networks.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-08</td><td class='std'>innovation toronto</td><td class='std'>How men and women organize their (online) social networks differently<br /><a href="http://www.innovationtoronto.com/2013/02/how-men-and-women-organize-their-online-social-networks-differently/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-08</td><td class='std'>scinexx</td><td class='std'>Online-Games: Frauen spielen anders<br /><a href="http://scinexx.de/wissen-aktuell-15557-2013-02-08.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-08</td><td class='std'>bild der wissenschaft</td><td class='std'>Netzwerken bringt's<br /><a href="http://www.wissenschaft.de/wissenschaft/news/316754.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-08</td><td class='std'>Medizinische Universität Wien</td><td class='std'>Frauen und Männer sind in ihren Netzwerken unterschiedlich organisiert<br /><a href="http://www.meduniwien.ac.at/homepage/news-und-topstories/?tx_ttnews%5Btt_news%5D=3239&amp;cHash=e8ad530e26"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>Santa Fe Institute News</td><td class='std'>How men and women organize their (online) social networks differently<br /><a href="http://www.santafe.edu/news/item/thurner-pardus-men-women-social-networks/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>NBC News</td><td class='std'>Women Out-Earn Men Online: Gaming Study<br /><a href="http://www.nbcnews.com/id/50731079/ns/technology_and_science-science/#.URU2A6XhrZ5"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>Instituto ciencia hoje</td><td class='std'>Sexo forte virtual<br /><a href="http://cienciahoje.uol.com.br/noticias/2013/02/sexo-forte-virtual"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>The Jace Hall show</td><td class='std'>Study: Women Outperform Men in MMO’s, Have Greater Chance of Survival<br /><a href="http://www.jacehallshow.com/news/gaming/industry/20130207/study-women-outperform-men-mmos-greater-chance-survival/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>Science Daily</td><td class='std'>How Men and Women Organize Their (Online) Social Networks Differently<br /><a href="http://www.sciencedaily.com/releases/2013/02/130207114703.htm"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>newswise</td><td class='std'>How Men and Women Organize Their (Online) Social Networks Differently<br /><a href="http://www.newswise.com/articles/how-men-and-women-organize-their-online-social-networks-differently"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>Wiener Zeitung</td><td class='std'>Evolutionsbiologie im Onlinespiel<br /><a href="http://www.wienerzeitung.at/themen_channel/wissen/mensch/522594_Evolutionsbiologie-im-Onlinespiel.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>Wiener Zeitung</td><td class='std'>Frauen und Männer spielen anders<br /><a href="http://www.wienerzeitung.at/themen_channel/wz_digital/spielplatz/522508_Frauen-und-Maenner-spielen-anders.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>LiveScience</td><td class='std'>Women Out-Earn Men Online: Gaming Study<br /><a href="http://www.livescience.com/26920-men-women-behavior-online.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>Science ORF.at</td><td class='std'>Frauen und Männer in virtuellen Welten<br /><a href="http://science.orf.at/stories/1712391/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>Der Standard</td><td class='std'>Frauen netzwerken anders als Männer<br /><a href="http://derstandard.at/1360161083469/Frauen-netzwerken-anders-als-Maenner"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-02-07</td><td class='std'>APA Kultur &amp; Gesellschaft</td><td class='std'>Online-Spiel hilft Sozialverhalten zu erforschen<br /><a href="http://science.apa.at/rubrik/kultur_und_gesellschaft/Online-Spiel_hilft_Sozialverhalten_zu_erforschen/SCI_20130207_SCI39351351611336694"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2013-01-28</td><td class='std'>Ö1 national radio</td><td class='std'>Dimensionen - Die Welt der Wissenschaft: Die Stadt als Freiluft-Computer<br /><a href="http://oe1.orf.at/programm/327022"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-10-31</td><td class='std'>Santa Fe Institute News</td><td class='std'>Online 'social petri dish' offers lessons about real-world human mobility<br /><a href="http://www.santafe.edu/news/item/thurner-csss-pardus-human-mobility/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-09</td><td class='std'>Santa Fe Institute Newsletter</td><td class='std'>Online 'social petri dish' offers insights about real-world human mobility<br /><a href="http://www.santafe.edu/media/update_pdf/SFI_UpdateSeptOct12_FNL.pdf"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-09-10</td><td class='std'>mysciencework.com</td><td class='std'>MMORPG players and Social Sciences<br /><a href="http://blog.mysciencework.com/en/2012/09/10/mmorpg-players-and-social-sciences.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-06-28</td><td class='std'>ABA - Invest in Austria Newsletter</td><td class='std'>A Petri Dish for Human Mobility<br /><a href="http://investinaustria.at/EN/Home/ABA+Newsletter+June+28+2012.aspx"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-06-19</td><td class='std'>Der Standard</td><td class='std'>Daten über Mann und Frau und alles andere<br /><a href="../downloads/article_derstandard02.pdf"><div class="filepdf">Article</div></a> &nbsp; <a href="http://derstandard.at/1339638391644/Virtuelle-Gesellschaft-Daten-ueber-Mann-und-Frau-und-alles-andere"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-06-18</td><td class='std'>Der Standard</td><td class='std'>Naturgesetzen menschlichen Gruppenverhaltens online auf der Spur<br /><a href="http://derstandard.at/1339637858578/Mobilitaet-in-sozialen-Systemen-Naturgesetzen-menschlichen-Gruppenverhaltens-online-auf-der-Spur"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-06-15</td><td class='std'>nature asia-pacific</td><td class='std'>&#x30AA;&#x30F3;&#x30E9;&#x30A4;&#x30F3;&#x30B2;&#x30FC;&#x30E0;&#x306E;&#x30D7;&#x30EC;&#x30A4;&#x30E4;&#x30FC;&#x306B;&#x898B;&#x308B;&#x30D2;&#x30C8;&#x306E;&#x79FB;&#x52D5;&#x6027;<br /><a href="http://www.natureasia.com/japan/highlights/details.php?id=1872"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-05-30</td><td class='std'>popmech.ru</td><td class='std'>&#x41C;&#x423;&#x416;&#x421;&#x41A;&#x418;&#x415; &#x418; &#x416;&#x415;&#x41D;&#x421;&#x41A;&#x418;&#x415; &#x421;&#x415;&#x422;&#x418;: &#x422;&#x41E;&#x41D;&#x41A;&#x41E;&#x421;&#x422;&#x418; &#x421;&#x412;&#x42F;&#x417;&#x418;<br /><a href="http://www.popmech.ru/article/11112-muzhskie-i-zhenskie-seti/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-05-24</td><td class='std'>InterDig</td><td class='std'>Estudio muestra las diferencias entre hombres y mujeres en el mundo virtual<br /><a href="http://www.inteldig.com/2012/05/estudio-muestra-las-diferencias-entre-hombres-y-mujeres-en-el-mundo-virtual/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-05-24</td><td class='std'>lenta.ru</td><td class='std'>&#x41E;&#x43D;&#x43B;&#x430;&#x439;&#x43D;-&#x438;&#x433;&#x440;&#x430; &#x43F;&#x43E;&#x43A;&#x430;&#x437;&#x430;&#x43B;&#x430; &#x440;&#x430;&#x437;&#x43B;&#x438;&#x447;&#x438;&#x44F; &#x432; &#x441;&#x43E;&#x446;&#x438;&#x430;&#x43B;&#x44C;&#x43D;&#x43E;&#x43C; &#x43F;&#x43E;&#x432;&#x435;&#x434;&#x435;&#x43D;&#x438;&#x438; &#x43C;&#x443;&#x436;&#x447;&#x438;&#x43D; &#x438; &#x436;&#x435;&#x43D;&#x449;&#x438;&#x43D;<br /><a href="http://lenta.ru/news/2012/05/24/network/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-05-23</td><td class='std'>Yahoo! Finance</td><td class='std'>Mars and Venus Online: How the Genders Differ in Their Use of Social Networks<br /><a href="http://finance.yahoo.com/news/mars-venus-online-genders-differ-152303448.html"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-05-23</td><td class='std'>The Atlantic</td><td class='std'>Mars and Venus Online: How the Genders Differ in Their Use of Social Networks<br /><a href="http://www.theatlantic.com/technology/archive/2012/05/mars-and-venus-online-how-the-genders-differ-in-their-use-of-social-networks/257571/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-05-23</td><td class='std'>MIT Technology Review</td><td class='std'>How Men and Women Manage Their Social Networks Differently<br /><a href="http://www.technologyreview.com/blog/arxiv/27870/"><div class="linkexternal">Online report</div></a></td></tr>
	    <tr><td class='std col1 date'>2012-03-04</td><td class='std'>Die Presse</td><td class='std'>Anonyme Online-Games: Das Gute im Menschen gibt es<br /><a href="http://diepresse.com/home/science/737109/Anonyme-OnlineGames_Das-Gute-im-Menschen-gibt-es?_vl_backlink=/home/science/index.do"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-02-16</td><td class='std'>MarketingArena</td><td class='std'>I confini della socializzazione: non tutto si può condividere<br /><a href="http://marketingarena.it/2012/02/16/i-confini-della-socializzazione-non-tutto-si-puo-condividere/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01-16</td><td class='std'>Therapy Toronto News</td><td class='std'>Study of virtual environment suggests people tend to behave prosocially even in absence of rules<br /><a href="http://therapytoronto.ca/news/?p=767"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>SOTT.net</td><td class='std'>Studie: Menschen verhalten sich auch ohne Regeln sozial<br /><a href="http://de.sott.net/articles/show/5721-Studie-Menschen-verhalten-sich-auch-ohne-Regeln-sozial"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>Forte.ee</td><td class='std'>Uuring: inimesed käituvad ühiskondlikult ja „hästi“ ka reegliteta maailmas<br /><a href="http://forte.delfi.ee/news/teadus/uuring-inimesed-kaituvad-uhiskondlikult-ja-hasti-ka-reegliteta-maailmas.d?id=63785294"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>Express.be</td><td class='std'>Individu gedraagt zich liever meedogend dan agressief<br /><a href="http://www.express.be/business/nl/hr/individu-gedraagt-zich-liever-meedogend-dan-agressief/160554.htm"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01-22</td><td class='std'>krone.at</td><td class='std'>Studie: Menschen verhalten sich auch ohne Regeln sozial<br /><a href="http://www.krone.at/Wissen/Studie_Menschen_verhalten_sich_auch_ohne_Regeln_sozial-So_ticken_wir-Story-308717"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01-18</td><td class='std'>Hyperbold</td><td class='std'>Aktuelle Studie: Verhalten sich Gesch&auml;ftsleute tats&auml;chlich wie Affen in Anz&uuml;gen?<br /><a href="http://opinion-formation-management.de/?p=445"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>Phys.Org</td><td class='std'>People behave socially and 'well' even without rules: study<br /><a href="http://www.physorg.com/news/2012-01-people-socially.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>Kleine Zeitung</td><td class='std'>Auch ohne Regel "lieb"</td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>Salzburger Nachrichten</td><td class='std'>Sozial handeln ohne Regeln</td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>studium.at</td><td class='std'>MedUni Wien: Menschen verhalten sich auch ohne vorgegebene Regeln sozial und mitfühlend<br /><a href="http://www.studium.at/158410-meduni-wien-menschen-verhalten-sich-auch-ohne-vorgegebene-regeln-sozial-und-mitfuehlend"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>wallstreet:online</td><td class='std'>Computerspieler erklären die Welt<br /><a href="http://www.wallstreet-online.de/nachricht/4307312-computerspieler-erklaeren-welt"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>extremnews</td><td class='std'>Computerspieler erklären die Welt<br /><a href="http://www.extremnews.com/berichte/wissenschaft/f5f213c50a31f1e"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>pressetext.com</td><td class='std'>Computerspieler erklären die Welt - Spieleranalyse zeigt: Respekt ensteht auch ohne Regeln<br /><a href="http://www.pressetext.com/news/20120114003"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>Focus online</td><td class='std'>Leben ohne Regeln: So tickt der Mensch<br /><a href="http://www.focus.de/wissen/wissenschaft/psychologie/leben-ohne-regeln-so-tickt-der-mensch_aid_702429.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>Jedlersdorfer Rundschau</td><td class='std'>Menschen verhalten sich auch ohne Regeln sozial und "gut"<br /><a href="http://www.jedlersdorfer-rundschau.net/news/menschen-verhalten-sich-auch-ohne-regeln-sozial-und-gut/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>Wiener Zeitung</td><td class='std'>Menschen verhalten sich auch ohne Regeln sozial und "gut"<br /><a href="http://www.wienerzeitung.at/themen_channel/wzwissen/mensch/426974_Menschen-verhalten-sich-auch-ohne-Regeln-sozial-und-gut.html"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01-13</td><td class='std'>Science ORF.at</td><td class='std'>Ohne Regeln bricht keine Anarchie aus<br /><a href="http://science.orf.at/stories/1693136/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>Tiroler Tageszeitung</td><td class='std'>Menschen verhalten sich auch ohne Regeln sozial und "gut"<br /><a href="http://www.tt.com/csp/cms/sites/tt/%C3%9Cberblick/Freizeit%C3%BCberblick/Leben/4138545-6/menschen-verhalten-sich-auch-ohne-regeln-sozial-und-gut.csp"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>visionair.nl</td><td class='std'>Waarom het goede uiteindelijk altijd wint<br /><a href="http://www.visionair.nl/wetenschap/waarom-het-goede-uiteindelijk-altijd-wint/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01-13</td><td class='std'>Medizinische Universität Wien</td><td class='std'>Menschen verhalten sich auch ohne Regeln sozial und "gut"<br /><a href="http://www.meduniwien.ac.at/homepage/news-und-topstories/?tx_ttnews[tt_news]=1996"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2012-01</td><td class='std'>Spektrum Direkt</td><td class='std'>Der Erdsimulator<br /><a href="http://www.wissenschaft-online.de/artikel/1127823&_z=859070"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2011-09</td><td class='std'>NOEMA Tecnología e Società</td><td class='std'>ECCS'11 a Vienna. Il commento<br /><a href="http://noemalab.eu/ideas/essay/eccs11-a-vienna-il-commento/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2011-09</td><td class='std'>Bricks</td><td class='std'>La Conferenza Europea di Vienna sui Sistemi Complessi<br /><a href="http://bricks.maieutiche.economia.unitn.it/?p=1575"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2011-09</td><td class='std'>Ö1 national radio</td><td class='std'>Dimensionen - Die Welt der Wissenschaft: Komplexe Systeme - Ordnung und Chaos in Natur und Gesellschaft<br /><a href="http://oe1.orf.at/programm/283934"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2011-07</td><td class='std'>MIT Technology Review</td><td class='std'>Virtual World Study Reveals The Origin of Good and Bad Behaviour Patterns<br /><a href="http://www.technologyreview.com/blog/arxiv/26967/"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2011-03</td><td class='std'>Wien live</td><td class='std'>80-dimensionale Ameisen</td></tr>
		<tr><td class='std col1 date'>2010-08</td><td class='std'>LaFlecha</td><td class='std'>Las relaciones virtuales son más estables que las habituales<br /><a href="http://www.laflecha.net/canales/blackhats/las-relaciones-virtuales-son-mas-estables-que-las-habituales?_xm=newsletter"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-08</td><td class='std'>Radio TV México</td><td class='std'>Las relaciones virtuales son más estables que las habituales<br /><a href="http://www.radiotvmexico.net/index.php?seccion=noticiaInd&recordID=2275"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2010-07</td><td class='std'>DRadio Wissen</td><td class='std'>Piraten und Händler im Weltraum - ein Modell unserer Gesellschaft?<br /><a href="http://wissen.dradio.de/index.33.isuv.html?dram:article_id=4468&sid=&random=c7c52f"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2010-07</td><td class='std'>Sverigeradio</td><td class='std'>Dataspelande bevisar gammal psykologisk teori<br /><a href="http://m.sverigesradio.se/site/index.aspx?artikel=3881140&unitid=406&offset=0"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2010-07</td><td class='std'>Global Computer Service</td><td class='std'>Positive Beziehungen halten uns zusammen<br /><a href="http://www.gcs.or.at/index.php?option=com_content&view=article&id=83:positive-beziehungen-halten-uns-zusammen&catid=1:news&Itemid=1"><div class="linkexternal">Online report</div></a></td></tr>
		<tr><td class='std col1 date'>2010-07</td><td class='std'>ORF Futurezone</td><td class='std'>Beziehungsanalysen im Onlinegame<br /><a href="http://futurezone.orf.at/stories/1655848/"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Musicaynoticias.cl</td><td class='std'>Validez de una teoria de interaccion social es demostrada con un videojuego para multijugadores<br /><a href="http://www.musicaynoticias.cl/content/view/899390/Validez-de-una-teoria-de-interaccion-social-es-demostrada-con-un-videojuego-para-multijugadores.html#content-top"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Estadao.com.br</td><td class='std'>Estudo usando videogame confirma que 'o amigo do inimigo é inimigo'<br /><a href="http://www.estadao.com.br/noticias/vidae,estudo-usando-videogame-confirma-que-o-amigo-do-inimigo-e-inimigo,583346,0.htm"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>iCT</td><td class='std'>Gra komputerowa dowodem na teori spoleczna<br /><a href="http://www.ict-pomorzezachodnie.pl/clients/news/607"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Catalunya Vanguardista</td><td class='std'>Human networks<br /><a href="http://www.catalunyavanguardista.com/en/?p=1156"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>GouvActu AdmiNet</td><td class='std'>L'ami de mon ennemi est vraiment mon ennemi<br /><a href="http://gouvactu.adminet.fr/l-ami-de-mon-ennemi-est-vraiment-mon-ennemi-synd00198203.html"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Southasianews</td><td class='std'>People prefer positive relationships to ensure stable social networks<br /><a href="http://www.southasianews.com/547052/People-prefer-positive-relationships-to-ensure-stable-social-networks.htm"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Salute</td><td class='std'>I NEMICI DEGLI AMICI SONO ANCHE NOSTRI NEMICI<br /><a href="http://salute.agi.it/primapagina/notizie/201007261420-hpg-rsa1025-i_nemici_degli_amici_sono_anche_nostri_nemici_studio-07"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Euzine</td><td class='std'>Der Freund meines Feindes ist wirklich mein Feind<br /><a href="http://euzine.eu/2010/07/24/der-freund-meines-feindes-ist-wirklich-mein-feind/"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Terradaily</td><td class='std'>The Friend Of My Enemy Is My Enemy<br /><a href="http://www.terradaily.com/reports/The_Friend_Of_My_Enemy_Is_My_Enemy_999.html"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Songshuhui</td><td class='std'>&#25932;&#20154;&#20043;&#21451;&#20035;&#21566;&#20043;&#25932;,&#20998;&#26512;&#34394;&#25311;&#28216;&#25103;&#35770;&#35777;&#32769;&#24515;&#29702;&#23398;&#29702;&#35770;<br /><a href="http://songshuhui.net/archives/40654.html"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Solidot</td><td class='std'>&#32593;&#28216;&#30740;&#31350;&#35777;&#26126;&#20154;&#38469;&#20114;&#21160;&#29702;&#35770;<br /><a href="http://science.solidot.org/science/10/07/26/0617237.shtml"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Indianews365</td><td class='std'>People prefer positive relationships to ensure stable social networks<br /><a href="http://www.indianews365.com/people-prefer-positive-relationships-to-ensure-stable-social-networks-1135"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Daily India</td><td class='std'>People prefer positive relationships to ensure stable social networks<br /><a href="http://www.dailyindia.com/show/387316.php"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>The Info Sage</td><td class='std'>People prefer positive relationships to ensure stable social networks<br /><a href="http://www.theinfosage.com/people-prefer-positive-relationships-to-ensure-stable-social-networks.html"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Medical News Today</td><td class='std'>Virtual Universe Study Proves 80-Year-Old Theory On How Humans Interact<br /><a href="http://www.medicalnewstoday.com/articles/195267.php"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Newstrack India</td><td class='std'>People prefer positive relationships to ensure stable social networks<br /><a href="http://www.newstrackindia.com/newsdetails/169839"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Daily Times India</td><td class='std'>People prefer positive relationships to ensure stable social networks<br /><a href="http://www.dailytimesindia.com/2010/07/143609.htm"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Labspaces</td><td class='std'>The friend of my enemy is my enemy<br /><a href="http://www.labspaces.net/105190/The_friend_of_my_enemy_is_my_enemy"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Science Centric</td><td class='std'>The friend of my enemy is my enemy<br /><a href="http://www.sciencecentric.com/news/10072027-the-friend-my-enemy-is-my-enemy.html"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Scientific Computing</td><td class='std'>The friend of my enemy is my enemy<br /><a href="http://www.scimag.com/news-the-friend-of-my-enemy-is-my-enemy-071910.aspx"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Naukowy</td><td class='std'>Przyjaciel mojego wroga jest rzeczywi?cie moim wrogiem<br /><a href="http://www.naukowy.pl/przyjaciel-mojego-wroga-jest-rzeczywiscie-moim-wrogiem-vt42724.htm"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Numerama</td><td class='std'>Un jeu massivement multijoueurs analysé pour démontrer les liens sociaux<br /><a href="http://www.numerama.com/magazine/16310-un-jeu-massivement-multijoueurs-analyse-pour-demontrer-les-liens-sociaux.html"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Slashdot</td><td class='std'>Study of MMOG Proves Human Interaction Theory<br /><a href="http://games.slashdot.org/story/10/07/25/2211218/Study-of-MMOG-Proves-Human-Interaction-Theory"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Softpedia</td><td class='std'>Positive Relationships Keep People Together<br /><a href="http://news.softpedia.com/news/Positive-Relationships-Keep-People-Together-148198.shtml"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Science Daily</td><td class='std'>"The Friend of My Enemy Is My Enemy": Virtual Universe Study Proves 80-Year-Old Theory on How Humans Interact<br /><a href="http://www.sciencedaily.com/releases/2010/07/100719162510.htm"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>APA</td><td class='std'>Onlinespiel als soziales Experiment<br /><a href="http://www.zukunftwissen.at/cms/zukunft-wissen/fti-und-wissenschaft/topnews_einzel.html?id=CMS1279600581113"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Imperial College London</td><td class='std'>'The friend of my enemy is my enemy': Virtual universe study proves 80 year old theory on how humans interact<br /><a href="http://www3.imperial.ac.uk/newsandeventspggrp/imperialcollege/newssummary/news_20-7-2010-10-22-28"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Medizinische Universität Wien</td><td class='std'>MedUni Wien - Physiker vermessen menschliche Gesellschaft in Onlinewelt<br /><a href="http://www.meduniwien.ac.at/homepage/news-und-topstories/?tx_ttnews[tt_news]=1405&cHash=0742566794"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Santa Fe Institute</td><td class='std'>The friend of my enemy is my enemy<br /><a href="http://santafe.edu/news/item/friend-my-enemy-my-enemy-Thurner/"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>OE24</td><td class='std'>300.000 "Pardus" Online-Gamer untersucht<br /><a href="http://www.oe24.at/digital/Pardus-Online-Spiel-Experiment-untersucht-0745423.ece"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>austria.com</td><td class='std'>Onlinespiel als Experiment<br /><a href="http://www.austria.com/news/chronik/artikel/onlinespiel-als-experiment/cn/news-20100719-03523664"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Phys.Org</td><td class='std'>The friend of my enemy is my enemy: Virtual universe study proves 80-year-old theory on how humans interact<br /><a href="http://www.physorg.com/news198764738.html"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Vorarlberg online</td><td class='std'>Onlinespiel als Experiment<br /><a href="http://www.vol.at/news/welt/artikel/onlinespiel-als-experiment/cn/news-20100719-03523664"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Der Standard</td><td class='std'>Soziale Gesetze von Freund und Feind<br /><a href="../downloads/article_derstandard01.pdf"><div class="filepdf">Article</div></a> &nbsp; <a href="http://derstandard.at/1277338473139/Soziale-Gesetze-von-Freund-und-Feind"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-07</td><td class='std'>Krone</td><td class='std'>Gesellschaft erstmals mittels Game "vermessen"<br /><a href="http://www.krone.at/Discover/Gesellschaft_erstmals_mittels_Game_vermessen-Durchbruch-Story-210840"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2010-01-08</td><td class='std'>Ö1 national radio</td><td class='std'>Dimensionen - Die Welt der Wissenschaft</td></tr>
        <tr><td class='std col1 date'>2009-11-14</td><td class='std'>Die Presse</td><td class='std'>Netzwerkanalysen: Ansteckung im Computer<br /><a href="http://diepresse.com/home/science/521733/index.do"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2008-02</td><td class='std'>T-Online</td><td class='std'>Pardus - Strategiegame aus Österreich</td></tr>
        <tr><td class='std col1 date'>2008-02</td><td class='std'>Radio Niederösterreich</td><td class='std'>Interview mit Michael Szell</td></tr>
        <tr><td class='std col1 date'>2008-02-04</td><td class='std'>Telekommunikations &amp; IT Report</td><td class='std'>Im Test: Pardus<br /><a href="http://www.report.at/index.php?option=com_content&view=article&id=28880"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2008-02</td><td class='std'>Exporter's Weekly</td><td class='std'>Globaler "Renner" mit nö. Computerspiel<br /><a href="../downloads/article_exportersweekly01.pdf"><div class="filepdf">Article</div></a></td></tr>
        <tr><td class='std col1 date'>2008-01-18</td><td class='std'>Wirtschaftspressedienst Niederösterreich</td><td class='std'>Computerspiel aus NÖ wurde zum weltweiten Renner<br /><a href="http://www.wirtschaftspressedienst.at/index.php?site=artikel_show&artikelid=3391&indexshow=1&ausgabenr=951"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2007-07</td><td class='std'>PC PowerPlay</td><td class='std'>Pardus: Der Newcomer aus Österreich<br /><a href="../downloads/article_pcpowerplay01.pdf"><div class="filepdf">Article</div></a></td></tr>
        <tr><td class='std col1 date'>2007-05</td><td class='std'>Honolulu Star-Bulletin</td><td class='std'>Click with online crowd - Play well with others? Try these games<br /><a href="http://starbulletin.com/2007/05/08/features/story01.html"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2007-05-29</td><td class='std'>Telekommunikations &amp; IT Report</td><td class='std'>Auf Erfolgskurs - Zuwächse bei Onlinespiel Pardus<br /><a href="http://www.report.at/index.php?option=com_content&view=article&id=28880"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2007-04</td><td class='std'>Wiener</td><td class='std'>Lost in Space<br /><a href="../downloads/article_wiener01.pdf"><div class="filepdf">Article</div></a></td></tr>
        <tr><td class='std col1 date'>2007-02-15</td><td class='std'>Telekommunikations &amp; IT Report</td><td class='std'>Der Communityeffekt - Pardus made in Pressbaum<br /><a href="../downloads/article_telekommunikationsitreport02.pdf"><div class="filepdf">Article</div></a></td></tr>
        <tr><td class='std col1 date'>2007-01-31</td><td class='std'>FM4 national radio</td><td class='std'>Interview mit Michael Szell</td></tr>
        <tr><td class='std col1 date'>2006-10</td><td class='std'>Stratics</td><td class='std'>Pardus - The Future is Here!</td></tr>
        <tr><td class='std col1 date'>2006-06-15</td><td class='std'>derStandard.at</td><td class='std'>"Pardus" - kostenloses Online-Spiel aus Österreich<br /><a href="http://derstandard.at/?url=/?id=2416055"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2006-05-15</td><td class='std'>Telekommunikations &amp; IT Report</td><td class='std'>"Größte Motivation" - Pardus: Erfolg für Community-Plattform<br /><a href="../downloads/article_telekommunikationsitreport01.pdf"><div class="filepdf">Article</div></a></td></tr>
        <tr><td class='std col1 date'>2005-12</td><td class='std'>GameOgre</td><td class='std'>Pardus - Best Free Online RPG of the Year 2005<br /><a href="http://www.gameogre.com/2005awards.htm"><div class="linkexternal">Online report</div></a></td></tr>
        <tr><td class='std col1 date'>2005-11-03</td><td class='std'>Telekom Austria</td><td class='std'>Online Universum Pardus</td></tr>
        <tr><td class='std col1 date'>2005-05</td><td class='std'>Progress - Das ÖH-Magazin</td><td class='std'>"Pardus" - kostenloses Online-Spiel aus Österreich</td></tr>
    </table>

    			<div class="clear"></div>
    		</div>
		</div>
	</div>


<?php
echo $footer;
?>

</body>
</html>
